-- Insert default notification templates for OwnItRight platform

INSERT INTO notification_templates (
  template_key,
  name,
  description,
  title_template,
  message_template,
  type,
  category,
  priority,
  requires_email,
  email_subject_template,
  email_body_template,
  is_active
) VALUES
(
  'REPORT_READY',
  'Report Ready',
  'Notification when a property report is ready for download',
  '{{reportType}} Report Ready',
  'Your {{reportType}} report for property {{propertyName}} is now ready for download.',
  'report',
  'report',
  'medium',
  true,
  'OwnItRight: Your {{reportType}} Report is Ready',
  '<h2>Your {{reportType}} Report is Ready!</h2><p>Dear Customer,</p><p>Your {{reportType}} report for the property {{propertyName}} has been completed and is now ready for download.</p><p>You can access your report through your dashboard or by clicking the link below.</p><p>Thank you for choosing OwnItRight for your property advisory needs.</p>'
),
(
  'BOOKING_CONFIRMED',
  'Booking Confirmed',
  'Notification when a site visit booking is confirmed',
  'Site Visit Booking Confirmed',
  'Your site visit for {{propertyName}} has been confirmed for {{visitDate}}.',
  'booking',
  'booking',
  'high',
  true,
  'OwnItRight: Site Visit Confirmed - {{propertyName}}',
  '<h2>Site Visit Booking Confirmed</h2><p>Dear Customer,</p><p>Your site visit for {{propertyName}} has been confirmed for {{visitDate}}.</p><p>Our representative will meet you at the property location. Please arrive on time for the best experience.</p><p>If you need to reschedule, please contact us at least 24 hours in advance.</p>'
),
(
  'PAYMENT_RECEIVED',
  'Payment Received',
  'Notification when a payment is successfully received',
  'Payment Confirmation',
  'We have received your payment of {{amount}} for {{service}}. Thank you!',
  'payment',
  'payment',
  'medium',
  true,
  'OwnItRight: Payment Received - {{amount}}',
  '<h2>Payment Confirmation</h2><p>Dear Customer,</p><p>We have successfully received your payment of {{amount}} for {{service}}.</p><p>Transaction details:</p><ul><li>Amount: {{amount}}</li><li>Service: {{service}}</li><li>Date: {{paymentDate}}</li></ul><p>Thank you for your business!</p>'
),
(
  'PROPERTY_MATCH',
  'Property Match Found',
  'Notification when a property matches user criteria',
  'New Property Match Found',
  'We found a property that matches your criteria: {{propertyName}} in {{location}}.',
  'property',
  'property',
  'medium',
  true,
  'OwnItRight: New Property Match - {{propertyName}}',
  '<h2>New Property Match Found!</h2><p>Dear Customer,</p><p>Great news! We found a property that matches your search criteria:</p><p><strong>{{propertyName}}</strong><br>Location: {{location}}<br>Price: {{price}}<br>Type: {{propertyType}}</p><p>View the property details and schedule a visit through your dashboard.</p>'
),
(
  'LEGAL_UPDATE',
  'Legal Due Diligence Update',
  'Notification when legal due diligence status is updated',
  'Legal Tracker Update',
  'Step {{stepNumber}} of your legal due diligence has been {{status}}.',
  'info',
  'report',
  'medium',
  true,
  'OwnItRight: Legal Due Diligence Update',
  '<h2>Legal Due Diligence Update</h2><p>Dear Customer,</p><p>Your legal due diligence process has been updated:</p><p>Step {{stepNumber}}: {{stepName}} - {{status}}</p><p>{{comments}}</p><p>Track your progress through the legal tracker in your dashboard.</p>'
),
(
  'WELCOME_USER',
  'Welcome New User',
  'Welcome message for new users',
  'Welcome to OwnItRight!',
  'Welcome to OwnItRight! We are here to help you find the perfect property with expert guidance.',
  'info',
  'system',
  'medium',
  true,
  'Welcome to OwnItRight - Your Property Advisory Partner',
  '<h2>Welcome to OwnItRight!</h2><p>Dear {{userName}},</p><p>Thank you for joining OwnItRight, your trusted property advisory platform.</p><p>We are here to help you:</p><ul><li>Find the perfect property</li><li>Get professional property valuations</li><li>Complete legal due diligence</li><li>Access CIVIL+MEP reports</li></ul><p>Start exploring properties and our services through your personalized dashboard.</p>'
),
(
  'SYSTEM_MAINTENANCE',
  'System Maintenance',
  'Notification about scheduled system maintenance',
  'Scheduled Maintenance Notice',
  'Our platform will undergo scheduled maintenance on {{maintenanceDate}} from {{startTime}} to {{endTime}}.',
  'warning',
  'system',
  'high',
  true,
  'OwnItRight: Scheduled Maintenance Notice',
  '<h2>Scheduled Maintenance Notice</h2><p>Dear Customer,</p><p>Our platform will undergo scheduled maintenance to improve your experience:</p><p>Date: {{maintenanceDate}}<br>Time: {{startTime}} to {{endTime}}</p><p>During this time, you may experience limited access to some features. We apologize for any inconvenience.</p>'
),
(
  'PRICE_ALERT',
  'Property Price Alert',
  'Notification when a property price changes',
  'Price Alert: {{propertyName}}',
  'The price of {{propertyName}} has {{priceChange}} to {{newPrice}}.',
  'info',
  'property',
  'medium',
  true,
  'OwnItRight: Price Alert - {{propertyName}}',
  '<h2>Property Price Alert</h2><p>Dear Customer,</p><p>The price of {{propertyName}} has been updated:</p><p>Previous Price: {{oldPrice}}<br>New Price: {{newPrice}}<br>Change: {{priceChange}}</p><p>This property is in your watchlist. Don''t miss out on this opportunity!</p>'
),
(
  'LEAD_FOLLOW_UP',
  'Lead Follow-up',
  'Follow-up notification for leads',
  'Follow-up: {{leadSubject}}',
  'This is a reminder to follow up on your inquiry about {{leadSubject}}.',
  'info',
  'lead',
  'low',
  false,
  null,
  null
),
(
  'URGENT_SECURITY',
  'Security Alert',
  'Urgent security-related notifications',
  'Security Alert: {{alertType}}',
  'Important security notice: {{alertMessage}}. Please take immediate action.',
  'error',
  'system',
  'urgent',
  true,
  'URGENT: OwnItRight Security Alert',
  '<h2 style="color: red;">URGENT SECURITY ALERT</h2><p>Dear Customer,</p><p>We have detected {{alertType}} on your account.</p><p>{{alertMessage}}</p><p>Please take immediate action to secure your account. If you did not authorize this activity, please contact our support team immediately.</p>'
);